codajoker/final_project_react_node_frontend

src/Button.styled.js, src/components/DailyCalorieIntake/DailyCalorieIntake.js, src/components/DailyCalorieIntake/DailyCalorieIntake.slyled.js, src/components/RightSidebar/RightSidebar.js, src/components/RightSidebar/RightSidebar.styled.js, src/variables/Variables.js
add DAILY CALORIE INTAKE and RIGHT SIDEBAR components markup
add BUTTON component
=> add components

package-lock.json, src/App.jsx, src/Container.styled.js, src/components/Header/Header.js, src/components/Header/Header.slyled.js, src/components/Logo/Logo.styled.js, src/components/Navigation/Navigation.js, src/components/Navigation/Navigation.styled.js, src/pages/DairyPage/DiaryPage.js, src/pages/DairyPage/DiaryPage.styled.js, src/pages/PreviewPage/PreviewPage.js
- Fix desktop breakpoint to 1280px;
- Fix container sizes;
- Add components to DiaryPage;
- Add Header to PrewiewPage and DiaryPage;
=> [fix] Fix header, container and add header

src/components/DailyCaloriesForm/DailyCaloriesForm.js, src/components/DailyCaloriesForm/DailyCaloriesForm.styled.js, src/validators/dailyCaloriesFormValidator.js
fixed validation calculator form, styles
=> fixed validation form, styles

src/components/Modal/Modal.css, src/components/Modal/Modal.js
The logic for opening and closing the window is not connected. Add an event to the button in the DailyCaloriesForm component.
=> Add modal window

package-lock.json, src/components/DailyCaloriesForm/DailyCaloriesForm.js, src/components/DailyCaloriesForm/DailyCaloriesForm.styled.js, src/index.js, src/pages/PreviewPage/PrewiewPage.styled.js, src/redux/dailyRate/dailyRateOperations.js, src/redux/dailyRate/dailyRateReducer.js, src/redux/dailyRate/dailyRateSelectors.js, src/redux/dailyRate/index.js, src/redux/store.js, src/services/dailyRateApi.js, src/validators/dailyCaloriesFormValidator.js
add redux for dc-form, fixed styles
=> Feature add redux for calculator

src/components/UserInfo/UserInfo.js
Добавив діспач на логаут.  Треба допомога з перенаправленням після логаута. код не працює
=> Userinfo.redux logic

src/components/UserInfo/UserInfo.js
Style finish.  останій коміт гілки
=> User info redux

src/components/DailyCalorieIntake/DailyCalorieIntake.js, src/components/DailyCaloriesForm/DailyCaloriesForm.js, src/components/DailyCaloriesForm/DailyCaloriesForm.styled.js, src/components/Header/Header.js, src/components/Modal/Modal.jsx, src/pages/PreviewPage/PreviewPage.js, src/redux/dailyRate/dailyRateOperations.js, src/redux/dailyRate/dailyRateSlice.js, src/services/dailyRateApi.js, src/services/users-api.js
refactoring main page and calculator page
=> Refactoring main page

src/components/UserInfo/UserInfo.js
=>  user-info  pravki

package-lock.json, package.json, src/components/DairyProductForm/DairyProductForm.js, src/components/DairyProductForm/DairyProductForm.styled.js, src/components/Header/Header.js, src/components/Header/Header.styled.js, src/components/Logo/Logo.js, src/components/MobileMenu/MenuNavigation.js, src/components/MobileMenu/MenuNavigation.styled.js, src/components/MobileSidebar/MobileSidebar.js, src/components/MobileSidebar/MobileSidebar.styled.js, src/components/Navigation/Navigation.js, src/components/Navigation/Navigation.styled.js, src/pages/DairyPage/DiaryPage.js, src/pages/DairyPage/DiaryPage.styled.js
- fix navigation on Logo;
- do formBtn disabled, when form inputs are empty
- Add navigation depend on isLoggedIn
- add react-detect-click-outside library and fix closing calendar on click outside him
- add some styles to Calendar
- add MobileSidebar and styles
=> [fix] Some bug fix

package-lock.json, src/App.jsx, src/components/DailyCaloriesForm/DailyCaloriesForm.js, src/components/DailyCaloriesForm/DailyCaloriesForm.styled.js, src/components/PrivateRoute/PrivateRoute.js, src/components/PublicRoute/publicRoute.js, src/pages/CalculatorPage/CalculatorPage.js
=> Add routes

src/redux/auth/authSlice.js
- fix it, because backend give data object
=> [fix] Fix authSlice

src/components/UserInfo/UserInfo.js, src/components/UserInfo/UserInfo.styled.jsx, src/pages/CalculatorPage/CalculatorPage.js, src/pages/PreviewPage/PreviewPage.js, src/services/users-api.js
=> User info new

src/components/UserInfo/UserInfo.js, src/components/UserInfo/UserInfo.styled.jsx
=> finished fixed

src/components/DairyProductList/DairyProductList.js, src/components/DairyProductList/DairyProductList.styled.jsx, src/components/DairyProductListItem/DairyProductListItem.js, src/pages/DairyPage/DiaryPage.js, src/redux/products/productsOperations.js, src/redux/products/productsSelectors.js, src/redux/products/productsSlice.js, src/services/productsApi.js
- Fix DairyProductsListItem key
- Fix positioning of DairyProductsList at tablet version
- Add redux logic of adding products to list
- Fix requests for getting products list and deleting product
- add selector getProductsList
- do some bug fix at DiaryPage
- fix productsOperations
=> [fix] Fix DairyPage list and redux logic

src/App.jsx, src/components/LoginForm/LoginForm.js, src/components/PrivateRoute/PrivateRoute.js, src/components/PublicRoute/PublicRoute.js
fixed private and public routes
=> fixed routes

package-lock.json, src/components/UserInfo/UserInfo.styled.jsx
=> user-info  fixed styles

src/App.jsx, src/components/LoginForm/LoginForm.js, src/components/PrivateRoute/PrivateRoute.js, src/components/PublicRoute/PublicRoute.js
=> fixed routes, login-form

src/components/DairyProductForm/DairyProductForm.js, src/components/DairyProductListItem/DairyProductListItem.js, src/components/DairyProductListItem/DairyProductListItem.styled.jsx, src/components/RightSidebar/RightSidebar.js, src/pages/DairyPage/DiaryPage.js, src/redux/products/productsSelectors.js, src/redux/products/productsSlice.js
- Add loader to DiaryPage
- Fix size of product title
- Remove unnecessary totalDayCalories from slice and add existingProduct checking
- remove unnecessary selector
=> [feat] Add loader and fix page render

src/App.jsx, src/index.js, src/pages/CalculatorPage/CalculatorPage.js, src/pages/DairyPage/DiaryPage.js, src/redux/auth/authOperations.js, src/redux/auth/authSlice.js, src/redux/dailyRate/dailyRateSlice.js, src/services/usersApi.js
- add currentUserRefresh that get info about user
- add refreshToken that get new token
- change refresh to refreshUser at dailyRateSlice
- change state at authSlice
- add refreshUser and refreshToken operations
- do refreshing token every 5 min and logOut user if isLoggedIn false
- do error handling with usingaxios.interceptors
=> [fix] Fix token refreshing

src/App.jsx, src/components/RightSidebar/RightSidebar.js, src/components/UserInfo/UserInfo.styled.jsx, src/redux/auth/authSelectors.js, src/redux/dailyRate/dailyRateSlice.js
- Fix styles of UserInfo
- add refreshing user dependency (userEmail)
=> [fix] Fix current user calories norm depend on user

src/pages/CalculatorPage/CalculatorPage.js
add mobile-sidebar in calc-page
=> add mobile-sidebar in calc-page

src/components/DailyCaloriesForm/DailyCaloriesForm.js, src/components/DailyCaloriesForm/DailyCaloriesForm.styled.js, src/pages/PreviewPage/PrewiewPage.styled.js, src/validators/dailyCaloriesFormValidator.js
fixed validation error-text, radio-btn, styled with PreviewPage
=> fixed calc-form

src/components/Modal/Modal.styled.js
- Remove border in mobile version of modal window
- Remove max width
=> [fix] Modal styles

src/components/UserInfo/UserInfo.js
=> [fix] User name

src/components/DailyCaloriesForm/DailyCaloriesForm.js, src/pages/PreviewPage/PrewiewPage.styled.js, src/validators/dailyCaloriesFormValidator.js
=> add fix to cacl-form

src/components/Modal/Modal.styled.js
- Remove border in mobile version of modal window
- Remove max width
=> [fix] Mobile modal styles

src/components/UserInfo/UserInfo.js, src/components/UserInfo/UserInfo.styled.jsx
- Fix name wrapping if name consists of two words
=> [fix] Name wrap

src/components/DairyProductListItem/DairyProductListItem.js
- Add a warning before deleting a product
=> [feat] Delete warning
